# These settings come from settings.yml, etc. No literals should be
# committed to this file.
default: &default
  adapter:        <%= Settings.rails.cable.adapter %>
  url:            <%= Settings.rails.cable.url %>
  channel_prefix: <%= Settings.rails.cable.channel_prefix %>

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
