# See settings.yml for rails.database. This adds a YAML alias of all values
# there, and then includes them in every environment.
# The development.yml, test.yml, and production.yml files under settings/
# have more specific values that are included for each matching environment.
#
# The DATABASE_URL environment variable will always override settings files.

<%=
YAML.dump({'settings' => Settings.rails.database.to_h.stringify_keys})
  .split("\n")
  .drop(2)
  .unshift('default: &default')
  .join("\n")
%>

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
