development:
  host: 'ez.test.datacite.org'
  port: 443
  shoulder: 'doi:10.5072/'
  use_ssl: true
  user: "umich.library"
  password: "1o^P78AxOxurMW"
test:
  host: 'ez.test.datacite.org'
  port: 443
  shoulder: 'doi:10.5072/'
  use_ssl: true
  user: "umich.library"
  password: "1o^P78AxOxurMW"
