# Import values from settings.yml, etc. This file should remain generic;
# that is, any literals or additional keys should be added to settings and
# imported here, except for one-off testing.

default: &default
  user:      <%= Settings.fedora.user %>
  password:  <%= Settings.fedora.password %>
  url:       <%= Settings.fedora.url %>
  base_path: <%= Settings.fedora.base_path %>

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
