development:
  archivist:
    - archivist1@example.com
  admin:
    - jhallida@indiana.edu
    - jvwitten@indiana.edu
    - rdfloyd@indiana.edu
    - didesilv@iu.edu
    - blancoj@umich.edu
    - fritx@umich.edu
    - fritx2@umich.edu
test:
  archivist:
    - archivist1@example.com
    - archivist2@example.com
    - leland_himself@example.com
  admin_policy_object_editor:
    - archivist1@example.com
  donor:
    - donor1@example.com
    - leland_himself@example.com
  researcher:
    - archivist1@example.com
    - researcher1@example.com
  patron:
    - patron1@example.com
    - leland_himself@example.com

production:
  # Add roles for users here.
