# Import values from settings.yml, etc. This file should remain generic;
# that is, any literals or additional keys should be added to settings and
# imported here, except for one-off testing.

default: &default
  url: <%= ENV['SOLR_URL'] || Settings.solr.url %>

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
